package es.nivel36.laie.ejb.app;

public enum StatisticPanelType {

	JOB_OFFERS, USERS_JOB_OFFERS, //
	COMPLETED_JOB_OFFERS, USERS_COMPLETED_JOB_OFFERS, //
	CANDIDATES, USERS_CANDIDATES, //
	JOB_SUBMISSIONS, USERS_JOB_SUBMISSIONS, //
	COMPLETED_JOB_SUBMISSIONS, USERS_COMPLETED_JOB_SUBMISSIONS, //
	COMMUNICATIONS, USERS_COMMUNICATIONS;
}
