image: maven:3.3.3

pipelines:

  custom:
    sonar:
      - step:
          caches:
            - maven
          script:
            - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_KEY -Dsonar.login=$SONAR_TOKEN

  default:
    - step:
        caches:
          - maven
        script: 
          - mvn clean verify