<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>igochan</groupId>
	<artifactId>ged</artifactId>
	<version>${ged.version}</version>
	<packaging>pom</packaging>
	<name>ged</name>
	<modules>
		<module>ged-ear</module>
		<module>ged-ejb</module>
		<module>ged-rest</module>
		<module>ged-web</module>
	</modules>

	<properties>
	<ged.version>0.0.3-SNAPSHOT</ged.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<javaee-api.version>7.0</javaee-api.version>
		<maven.compiler.target>1.8</maven.compiler.target>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.plugin.version>3.3</maven.compiler.plugin.version>
		<maven.ear.plugin.version>2.10</maven.ear.plugin.version>
		<maven.war.plugin.version>2.6</maven.war.plugin.version>
		<maven.ejb.plugin.version>2.5</maven.ejb.plugin.version>
		<hibernate-search.version>5.5.4.Final</hibernate-search.version>
		<infinispan.version>8.2.4.Final</infinispan.version>
		<font-awesome.version>4.5.0</font-awesome.version>
		<version.pdfbox>1.8.6</version.pdfbox>
		<poi.version>3.14</poi.version>
		<omnifaces.version>2.2</omnifaces.version>
		<version.commons-fileupload>1.3</version.commons-fileupload>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.infinispan</groupId>
				<artifactId>infinispan-core</artifactId>
				<version>${infinispan.version}</version>
				<scope>provided</scope>
			</dependency>

			<dependency>
				<groupId>org.webjars</groupId>
				<artifactId>font-awesome</artifactId>
				<version>${font-awesome.version}</version>
			</dependency>

			<dependency>
				<groupId>org.omnifaces</groupId>
				<artifactId>omnifaces</artifactId>
				<version>${omnifaces.version}</version>
			</dependency>

			<dependency>
				<groupId>org.hibernate</groupId>
				<artifactId>hibernate-search-orm</artifactId>
				<version>${hibernate-search.version}</version>
				<scope>provided</scope>
			</dependency>

			<dependency>
				<groupId>igochan</groupId>
				<artifactId>ged-ejb</artifactId>
				<version>${ged.version}</version>
				<type>ejb</type>
			</dependency>

			<dependency>
				<groupId>igochan</groupId>
				<artifactId>ged-web</artifactId>
				<version>${ged.version}</version>
				<type>war</type>
				<scope>compile</scope>
			</dependency>

			<dependency>
				<groupId>igochan</groupId>
				<artifactId>ged-rest</artifactId>
				<version>${ged.version}</version>
				<type>war</type>
				<scope>compile</scope>
			</dependency>

			<dependency>
				<groupId>javax</groupId>
				<artifactId>javaee-api</artifactId>
				<version>${javaee-api.version}</version>
				<scope>provided</scope>
			</dependency>

			<dependency>
				<groupId>org.apache.pdfbox</groupId>
				<artifactId>pdfbox</artifactId>
				<version>${version.pdfbox}</version>
			</dependency>

			<dependency>
				<groupId>org.apache.poi</groupId>
				<artifactId>poi</artifactId>
				<version>${poi.version}</version>
			</dependency>

			<dependency>
				<groupId>commons-fileupload</groupId>
				<artifactId>commons-fileupload</artifactId>
				<version>${version.commons-fileupload}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<finalName>ged-web</finalName>
		<pluginManagement>
			<plugins>
				<plugin>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${maven.compiler.plugin.version}</version>
					<configuration>
						<source>${maven.compiler.source}</source>
						<target>${maven.compiler.target}</target>
					</configuration>
				</plugin>
				<plugin>
					<artifactId>maven-ejb-plugin</artifactId>
					<version>${maven.ejb.plugin.version}</version>
					<configuration>
						<ejbVersion>3.2</ejbVersion>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-ear-plugin</artifactId>
					<version>${maven.ear.plugin.version}</version>
					<configuration>
						<version>7</version>
						<defaultLibBundleDir>lib</defaultLibBundleDir>
						<modules>
							<webModule>
								<groupId>igochan</groupId>
								<artifactId>ged-rest</artifactId>
								<contextRoot>/rest</contextRoot>
							</webModule>
							<webModule>
								<groupId>igochan</groupId>
								<artifactId>ged-web</artifactId>
								<contextRoot>/web</contextRoot>
							</webModule>
							<ejbModule>
								<groupId>igochan</groupId>
								<artifactId>ged-ejb</artifactId>
							</ejbModule>
						</modules>
						<generateApplicationXml>true</generateApplicationXml>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-war-plugin</artifactId>
					<version>${maven.war.plugin.version}</version>
					<configuration>
						<failOnMissingWebXml>false</failOnMissingWebXml>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>