<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>igochan</groupId>
		<artifactId>ged</artifactId>
		<version>0.6.0-SNAPSHOT</version>
		<relativePath>..</relativePath>
	</parent>

	<artifactId>ged-ear</artifactId>
	<packaging>ear</packaging>

	<dependencies>
		<dependency>
			<groupId>igochan</groupId>
			<artifactId>ged-web</artifactId>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>igochan</groupId>
			<artifactId>ged-api</artifactId>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>igochan</groupId>
			<artifactId>ged-ejb</artifactId>
			<type>ejb</type>
		</dependency>
	</dependencies>

	<build>
		<finalName>ged</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ear-plugin</artifactId>
				<configuration>
					<version>8</version>
					<defaultLibBundleDir>lib</defaultLibBundleDir>
					<modules>
						<webModule>
							<groupId>igochan</groupId>
							<artifactId>ged-api</artifactId>
							<contextRoot>/api</contextRoot>
						</webModule>
						<webModule>
							<groupId>igochan</groupId>
							<artifactId>ged-web</artifactId>
							<contextRoot>/web</contextRoot>
						</webModule>
						<ejbModule>
							<groupId>igochan</groupId>
							<artifactId>ged-ejb</artifactId>
						</ejbModule>
					</modules>
					<outputFileNameMapping>@{artifactId}@-@{version}@@{dashClassifier?}@.@{extension}@</outputFileNameMapping>
					<generateApplicationXml>true</generateApplicationXml>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.wildfly.plugins</groupId>
				<artifactId>wildfly-maven-plugin</artifactId>
				<version>1.2.2.Final</version>
				<configuration>
					<hostname>${wildfly-hostname}</hostname>
					<port>${wildfly-port}</port>
					<username>${wildfly-username}</username>
					<password>${wildfly-password}</password>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>