<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<packaging>pom</packaging>

	<parent>
		<groupId>es.nivel36</groupId>
		<artifactId>laie</artifactId>
		<version>0.9.8-SNAPSHOT</version>
		<relativePath>..</relativePath>
	</parent>

	<artifactId>nivel36-login</artifactId>

	<modules>
		<module>nivel36-login-jsf</module>
		<module>nivel36-login-ejb</module>
	</modules>
</project>
