/*
* Laie
* Copyright (C) 2021  Abel Ferrer
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package es.nivel36.laie.core.service;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.Version;

/**
 * Abstract class from which all Entities of the application must inherit.
 * 
 * @author Abel Ferrer
 *
 */
@MappedSuperclass
public abstract class AbstractEntity implements Serializable {

	private static final long serialVersionUID = -8883886738746115174L;

	////////////////////////////////////////////////////////////////////////////
	// VARIABLES
	////////////////////////////////////////////////////////////////////////////

	@Id
	@GeneratedValue
	private long id;

	@Version
	private long version;

	////////////////////////////////////////////////////////////////////////////
	// PUBLIC
	////////////////////////////////////////////////////////////////////////////

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(final Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (this.getClass() != obj.getClass()) {
			return false;
		}
		final AbstractEntity other = (AbstractEntity) obj;
		return (this.id == other.id) && (this.version == other.version);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		return Objects.hash(this.id, this.version);
	}

	////////////////////////////////////////////////////////////////////////////
	// GETTERS
	////////////////////////////////////////////////////////////////////////////

	/**
	 * Returns the entity identifier. This value is auto incremental and is
	 * automatically generated by the ORM.
	 * 
	 * @return <tt>long</tt> with the id of the entity
	 */
	public long getId() {
		return this.id;
	}

	/**
	 * Returns the entity version. This value is auto incremental and is
	 * automatically generated by the ORM.
	 * 
	 * @return <tt>long</tt> with the version of the entity
	 */
	public long getVersion() {
		return this.version;
	}

	////////////////////////////////////////////////////////////////////////////
	// SETTERS
	////////////////////////////////////////////////////////////////////////////

	/**
	 * This method is public by ORM requirements, but should not be used.
	 */
	public void setId(final long id) {
		this.id = id;
	}

	/**
	 * This method is public by ORM requirements, but should not be used.
	 */
	public void setVersion(final long version) {
		this.version = version;
	}
}
